---
- name: Creating a nagios group
  group:
    name: nagcmd
    state: present

- name: Creating a nagios user
  user:
    name: "{{ nagios_user }}"
    comment: "Nagios User"
    password: "{{ nagios_pass | password_hash('sha512') }}"
    group: nagcmd

- name: Download and unarchive Nagios Core
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz
    dest: /tmp/
    remote_src: yes
  register: nagios_source

- name: Create Makefile
  shell: cd /tmp/nagioscore-nagios-4.4.5; sh /tmp/nagioscore-nagios-4.4.5/configure --with-httpd-conf=/etc/apache2/sites-enabled
  register: make_file
  when: nagios_source.changed

- name: Compile from source
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: all
  become: yes
  when: make_file.changed

- name: Create user and group
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-groups-users
  become: yes
  when: make_file.changed

- name: Add www-data user to nagios group
  user:
    name: www-data
    groups: nagios
    append: yes

- name: Install binaries
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install
  become: yes
  when: make_file.changed

- name: Install service/daemon
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-daemoninit
  become: yes
  when: make_file.changed

- name: Install command mode
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-commandmode
  become: yes
  when: make_file.changed

- name: Install configuration files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-config
  become: yes
  when: make_file.changed

- name: Install apache config files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-webconf
  become: yes
  when: make_file.changed
  register: install_webconf

- name: Enable rewrite module
  apache2_module:
    state: present
    name: rewrite

- name: Enable cgi module
  apache2_module:
    state: present
    name: cgi

- name: Restart apache2
  service:
    name: apache2
    state: restarted
  when: install_webconf.changed

- name: Start and enable nagios
  service:
    name: nagios
    state: started
    enabled: yes
  when: install_webconf.changed


